### ISSUE TITLE
INstall Error

### ISSUE THREAD

**Issue by Dazmed707** [Johnler/Wi-Ploit#2]
Parrot 4.9.1
sudo bash Installer
![image](https://user-images.githubusercontent.com/35184132/82112844-813a3c80-9740-11ea-8a86-881082bb97d3.png)
sudo bash Wi-Ploit
![image](https://user-images.githubusercontent.com/35184132/82112863-9a42ed80-9740-11ea-9688-c13c4e386a6a.png)

**Comment by Johnler** [comment]
I think Parrot os removed Pyrit package on apt
I never tried ParrotOs.
Try manually installing the packages that didn't installed by the scripts.
Example:
sudo apt-get install pyrit

**Comment by Dazmed707** [comment]
in parrot 4.7 it was going well
in the update of 4.9.1 it already gives that error

**Comment by Johnler** [comment]
I think I will try ParrotOS with this.

**Comment by Johnler** [comment]
Try to confirm if pyrit already installed in your parrotos

**Comment by Dazmed707** [comment]
I already looked for it and it is not installed either in the parrot repositories
I tried to compile pyrit but it gave me an error installing a dependency with pip

**Comment by Johnler** [comment]
I've read the latest release of ParrotOs and Kali, so I will be updating the scripts, removing some python2 tools, one of them is pyrit but in the good side pyrit is now migrating for python3

**Comment by Johnler** [comment]
New release is now Uploaded.
Check it out.

**Comment by Dazmed707** [comment]
ok thanks :)
Wi-PLoit found today
